# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    env_file:
      - .env

volumes:
  app_data:

networks:
  default:
    driver: bridge
