services:
  web:
    image: collaborative_editor
    build: .
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
      - /app/assets/node_modules
      - /app/priv/static/assets
    environment:
      - MIX_ENV=dev
      - PHX_SERVER=true
    stdin_open: true
    tty: true